name: End-to-end tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Atualize para a versão v3 que suporta Node.js 20

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Certifique-se de usar a última versão que suporta Node.js 20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5 # Atualize para a versão v5 que suporta Node.js 20
        with:
          start: npm start
